// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eiY13XR0DGK5dPmxW24uWBkggmsuhKw',
    appId: '1:504591956242:web:3da68dbdd60b2d57fe1bcb',
    messagingSenderId: '504591956242',
    projectId: 'photo-headquarters',
    authDomain: 'photo-headquarters.firebaseapp.com',
    storageBucket: 'photo-headquarters.appspot.com',
    measurementId: 'G-NRWWWGHER0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcC4t513faG1F5NHMNr6zP52_x-pGD4Y8',
    appId: '1:504591956242:android:e9c6338d5a432e51fe1bcb',
    messagingSenderId: '504591956242',
    projectId: 'photo-headquarters',
    storageBucket: 'photo-headquarters.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRFH6FPnV9Vs-w4bEv61bIUZM2my9wTc',
    appId: '1:504591956242:ios:c22387c882bc43defe1bcb',
    messagingSenderId: '504591956242',
    projectId: 'photo-headquarters',
    storageBucket: 'photo-headquarters.appspot.com',
    iosClientId: '504591956242-ovp3sgc46doe8djobg9q6g5c6q0qkfh1.apps.googleusercontent.com',
    iosBundleId: 'dev.psychoballer.photoheadquarters',
  );
}
